apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: gcr.io/massive-mantra-474000-c4/worker:v1
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: MINIO_HOST
          value: "minio-proj.minio-ns:9000"
        - name: MINIO_USER
          value: "rootuser"
        - name: MINIO_PASS
          value: "rootpass123"
        resources:
          requests:
            memory: "6Gi"
            cpu: "2"
          limits:
            memory: "8Gi"
            cpu: "4"
