apiVersion: v1
kind: Namespace
metadata:
  name: minio-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-proj
  namespace: minio-ns
spec:
  selector:
    matchLabels:
      app: minio
  replicas: 1
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:latest
        args:
        - server
        - /data
        - --console-address
        - ":9001"
        env:
        - name: MINIO_ROOT_USER
          value: "rootuser"
        - name: MINIO_ROOT_PASSWORD
          value: "rootpass123"
        ports:
        - containerPort: 9000
        - containerPort: 9001
        resources:
          requests:
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: minio-proj
  namespace: minio-ns
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: api
    - port: 9001
      targetPort: 9001
      protocol: TCP
      name: console
  selector:
    app: minio
